name: Semgrep

on:
  # Scan changed files in PRs, block on new issues only (existing issues ignored)
  pull_request:

  push:
    branches: ["dev", "main"]

  schedule:
    - cron: '23 20 * * 1'

  # Manually trigger the workflow
  workflow_dispatch:

jobs:
  semgrep:
    name: Scan
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 #v4.2.2

      - run: semgrep ci --sarif > semgrep.sarif
        env:
          SEMGREP_RULES: >- # more at semgrep.dev/explore
            p/security-audit
            p/secrets
            p/owasp-top-ten

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387 #v3.28.16 
        with:
          sarif_file: semgrep.sarif
        if: always()
